#!/bin/bash

#wall=$(find ~/Github/wallpapers-old/ -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)
wall=$(find ~/Pictures/wallpapers/ -type f -name "*.jpg" -o -name "*.png" | shuf -n 1)
xwallpaper --zoom $wall
#wal -c
#wal -i $wall
