live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"
opacity = 0.85
blur = true
[window.dimensions]
columns = 110
lines = 35

[window.padding]
x = 0
y = 0

[font]
size = 14

[selection]
save_to_clipboard = true
